// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_DGII.Data;

#nullable disable

namespace Prueba_DGII.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba_DGII.Models.ComprobanteFiscal", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ContribuyenteId")
                        .HasColumnType("int");

                    b.Property<double?>("Itbis18")
                        .HasColumnType("float");

                    b.Property<double?>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("NCF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RncCedula")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuyenteId");

                    b.ToTable("ComprobantesFiscales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContribuyenteId = 1,
                            Itbis18 = 36.0,
                            Monto = 200.0,
                            NCF = "E310000000001",
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 2,
                            ContribuyenteId = 1,
                            Itbis18 = 180.0,
                            Monto = 1000.0,
                            NCF = "E310000000002",
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 3,
                            ContribuyenteId = 2,
                            Itbis18 = 90.0,
                            Monto = 500.0,
                            NCF = "E310000000003",
                            RncCedula = "123456789"
                        });
                });

            modelBuilder.Entity("Prueba_DGII.Models.Contribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RncCedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contribuyentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estatus = "activo",
                            Nombre = "JUAN PEREZ",
                            RncCedula = "98754321012",
                            Tipo = "PERSONA FISICA"
                        },
                        new
                        {
                            Id = 2,
                            Estatus = "inactivo",
                            Nombre = "FARMACIA TU SALUD",
                            RncCedula = "123456789",
                            Tipo = "PERSONA JURIDICA"
                        });
                });

            modelBuilder.Entity("Prueba_DGII.Models.ComprobanteFiscal", b =>
                {
                    b.HasOne("Prueba_DGII.Models.Contribuyente", "Contribuyente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("ContribuyenteId");

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("Prueba_DGII.Models.Contribuyente", b =>
                {
                    b.Navigation("Comprobantes");
                });
#pragma warning restore 612, 618
        }
    }
}
